### ISSUE TITLE
Mod crashes Minecraft even by itself

### ISSUE THREAD

**Issue by HiWord9** [Miracle-Studio/SPWorlds-Nav#1]
Mod prevents minecraft from launching even if only fabric-api and spwn are in mods folder.
![image_2023-11-04_00-58-42 (2)](https://github.com/Miracle-Studio/SPWorlds-Nav/assets/46609661/5caef0fe-9488-4059-8882-d5815a7a856e)
Getting this error instead of launch. Shows up both on fabric and on quilt, checked with fabric-api 0.90 and qfapi 0.85 and 0.90.
Also i've tryed to change java version but it still won't work on java 19 and java 21.
![image](https://github.com/Miracle-Studio/SPWorlds-Nav/assets/46609661/32d3a7b5-a429-4b5b-b8d8-18d99fb92ddd)
![image](https://github.com/Miracle-Studio/SPWorlds-Nav/assets/46609661/e90933c0-9d6a-41fd-bc83-d7010318c029)

**Comment by MeiNanziiii** [comment]
починил в 0.1.1
