### ISSUE TITLE
Minecraft text breaks randomly after game launch

### ISSUE THREAD

**Issue by aladairmaxwell** [Miracle-Studio/SPWorlds-Nav#2]
![image](https://github.com/Miracle-Studio/SPWorlds-Nav/assets/69295711/aa06d5a9-526c-48e4-a320-5641cd0d96a8)
Using Fabric 1.20.1, adding this mod to my modpack this error happens.

I can restart the game and all symbols can be restored, or may not.

Also can't join singleplayer world or server.

What should I do?

[latest.log](https://github.com/Miracle-Studio/SPWorlds-Nav/files/14392635/latest.log)

**Comment by MeiNanziiii** [comment]
Delete dashloader
